import random
print("")
print("D20")
print(random.randint(1,20))
print("")
print("D100")
print(random.randint(1,100))
print("")
print("D6")
print(random.randint(1,6)) 
print("")
print("D4")
print(random.randint(1,4))  
print("")
print("D12")  
print(random.randint(1,12)) 
print("")
print("D7") 
print(random.randint(1,7)) 
print("")
print("D8")   
print(random.randint(1,8)) 
print("")
print("D10")   
print(random.randint(1,10))
    

    
